import './globals.css'
import Footer from '@/components/footer';

export const metadata = {
  title: 'Khokphochai hospital',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col justify-between bg-neutral-50">
        {children}
        <Footer />
      </body>
    </html>
  )
}
