"use client"

import './globals.css'
import React, { useState, useEffect, createContext } from 'react';
import Footer from '@/components/footer';

export const metadata = {
  title: 'Khokphochai hospital',
  description: 'Generated by create next app',
}

export const UserContext = createContext()

const liffId = process.env.NEXT_PUBLIC_LIFF_ID

export default function RootLayout({ children }) {
  const [user, setUser] = useState({
    "userId": "uuid",
    "displayName": "name",
    "statusMessage": "status message",
    "pictureUrl": "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png"
  })

  // useEffect(async () => {
  //     const liff = (await import('@line/liff')).default
  //     try {
  //         await liff.init({ liffId });
  //     } catch (error) {
  //         console.error('liff init error', error.message)
  //     }
  //     if (liff.isLoggedIn()) {
  //         const profile = await liff.getProfile()
  //         console.log(profile)
  //         setUser(profile)
  //     } else {
  //         liff.login();
  //     }
  // }, [])

  return (
    <html lang="en">
      <body>
        <UserContext.Provider value={user}>
          <div className="flex flex-col justify-between bg-neutral-50">
            {children}
            <Footer />
          </div>
        </UserContext.Provider>
      </body>
    </html>
  )
}
